-- INNER JOIN
-- 0 - QUERO RECUPERAR TODOS OS PEDIDOS FEITOS NA PIZZARIA ATÉ O MOMENTO
SELECT PV.DATA_PEDIDO, PV.VLR_PEDIDO_VENDA, C.NOME AS NOME_CLIENTE, 
V.NOME AS NOME_VENDEDOR, FP.DES_FORMA_PAGAMENTO, P.NOME AS NOME_PRODUTO, 
TP.DES_TIPO_PRODUTO
FROM PEDIDO_VENDA PV
INNER JOIN CLIENTE C ON C.COD_CLIENTE = PV.COD_CLIENTE 
INNER JOIN VENDEDOR V ON V.COD_VENDEDOR = PV.COD_VENDEDOR
INNER JOIN FORMA_PAGAMENTO FP ON FP.COD_FORMA_PAGAMENTO = PV.COD_FORMA_PAGAMENTO
INNER JOIN ITEM_PEDIDO_VENDA IPV ON IPV.COD_PEDIDO_VENDA = PV.COD_PEDIDO_VENDA
INNER JOIN PRODUTO P ON P.COD_PRODUTO = IPV.COD_PRODUTO
INNER JOIN TIPO_PRODUTO TP ON TP.COD_TIPO_PRODUTO = P.COD_TIPO_PRODUTO;

-- INNER JOIN
-- 1 - BUSCAR TODOS OS DOCUMENTOS CADASTRADOS X PEDIDOS COMPRADOS
SELECT PC.VLR_PEDIDO_COMPRA, F.NOME AS NOME_FORNECEDOR,
P.VLR_PRODUTO_COMPRA, P.NOME AS NOME_PRODUTO
FROM PEDIDO_COMPRA PC
INNER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = PV.COD_FORNECEDOR 
INNER JOIN ITEM_PEDIDO_VENDA IPV ON IPV.COD_PEDIDO_VENDA = PV.COD_PEDIDO_VENDA
INNER JOIN PRODUTO P ON P.COD_PRODUTO = IPV.COD_PRODUTO;


-- INNER JOIN
-- 2 - TODAS AS COTAÇÕES REALIZADAS
SELECT C.VLR_COTACAO, F.NOME AS NOME_FORNECEDOR, P.NOME AS NOME_PRODUTO
FROM COTACAO C
INNER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = C.COD_FORNECEDOR
INNER JOIN PRODUTO P ON P.COD_PRODUTO = C.COD_PRODUTO;

-- INNER JOIN
-- 3 - PRODUTOS VENDIDOS
SELECT IPV.COD_PRODUTO, P.NOME AS NOME_PRODUTO, QTD_ITEM_PEDIDO_VENDA
FROM ITEM_PEDIDO_VENDA IPV
INNER JOIN PRODUTO P ON P.COD_PRODUTO = IPV.COD_PRODUTO;

-- INNER JOIN
-- 4 - SIRUAÇÃO DO PEDIDO DE VENDA
SELECT PV.COD_PEDIDO_VENDA, PV.DATA_PEDIDO, PV.VLR_PEDIDO_VENDA, C.NOME AS NOME_CLIENTE
SP.STATUS_PEDIDO
FROM PEDIDO_VENDA PV
INNER JOIN CLIENTE C ON PV.COD_CLIENTE = C.COD_CLIENTE 
INNER JOIN SITUACAO_PEDIDO SP ON PV.COD_SITUACAO = SP.COD_SITUACAO_PEDIDO;

-- INNER JOIN
-- 5 - TODAS AS COTAÇÕES REALIZADAS COM UNIDADE DE MEDIDA
SELECT C.VLR_COTACAO, C.UNIDADE_MEDIDA, F.NOME AS NOME_FORNECEDOR 
FROM COTACAO C
INNER JOIN FORNECEDOR F ON C.COD_FORNECEDOR = F.COD_FORNECEDOR;

-- LEFT JOIN
-- 0 - QUERO TRAZER TODOS OS VENDEDORES CADASTRADOS
SELECT V.NOME AS NOME_VENDEDOR, PV.COD_PEDIDO_VENDA, PV.DATA_PEDIDO
FROM VENDEDOR V
LEFT JOIN PEDIDO_VENDA, PV ON V.COD_VENDEDOR = PV.COD_VENDEDOR;

-- RIGHT OUTER JOIN
-- 1 - BUSCAR TODOS OS FORNECEDORES CADASTRADOS MESMO SEM COMPRAS REALIZADAS
SELECT PC.VLR_PEDIDO_COMPRA, F.NOME AS NOME_FORNECEDOR,
P.VLR_PRODUTO_COMPRA, P.NOME AS NOME_PRODUTO
FROM PEDIDO_COMPRA PC
RIGHT OUTER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = PC.COD_FORNECEDOR
RIGHT OUTER JOIN PRODUTO P ON P.COD_PRODUTO = IPC.COD_PRODUTO;

-- 2 - TODAS AS COTAÇÕES REALIZADAS MESMO SEM SEREM EFETIVADAS
SELECT C.VLR_COTACAO, F.NOME AS NOME_FORNECEDOR, P.NOME AS NOME_PRODUTO
FROM COTACAO C
RIGHT OUTER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = C.COD_FORNECEDOR
RIGHT OUTER JOIN PRODUTO P ON P.COD_PRODUTO = C.COD_PRODUTO;

-- 3 - TODOS OS PEDIDOS DE VENDAS MESMO SEM VENDEDOR CADASTRADO
SELECT V.NOME AS NOME_VENDEDOR, PV.COD_PEDIDO_VENDA, PV.DATA_PEDIDO
FROM PEDIDO_VENDA PV
RIGHT JOIN VENDEDOR V ON PV.COD_VENDEDOR = V.COD_VENDEDOR;

-- FULL OUTER JOIN
-- 1 - BUSCAR TODOS OS FORNECEDORES CADASTRADOS COM TODOS OS DEPIDOS DE COMPRA
SELECT PC.VLR_PEDIDO_COMPRA, F.NOME AS NOME_FORNECEDOR, P.VLR_PRODUTO_COMPRA, 
P.NOME AS NOME_PRODUTO
FROM PEDIDO_COMPRA PC
FULL OUTER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = PC.COD_FORNECEDOR
FULL OUTER JOIN ITEM_PEDIDO_VENDA IPC ON IPC.COD_PEDIDO_COMPRA = PC.COD_PEDIDO_COMPRA
FULL OUTER JOIN PRODUTO P ON P.COD_PRODUTO = IPC.COD_PRODUTO;

-- 2 - TODAS AS COTAÇÕES REALIZADAS COM TODOS OS PRODUTOS
SELECT C.VLR_COTACAO, F.NOME AS NOME_FORNECEDOR, P.NOME AS NOME_PRODUTO
FROM COTACAO C
FULL OUTER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = C.COD_FORNECEDOR
FULL OUTER JOIN PRODUTO P ON P.COD_PRODUTO = C.COD_PRODUTO;